不具合項目203番の修正
kensuma-1122/kensuma pull request #400
Opened 2023-07-14 21:58 UTC by badminto

### 概要
_PR概要を記述する_

### タスク
- [x] なし
- [ ] あり _(タスクのリンクがあれば貼る)_

### 実装内容・手法
_実装内容や、問題の解決手法を記述する_

### 実装画像などあれば添付する

2023-07-15 07:25 UTC, HiroakiKonnno requested changes
コメントしたので確認をお願いいたします！
そもそも下請けの外国人登録がないとPDFのボタンを押したときに、エラーメッセージ(外国人の登録者がいませんなのか作業中ですなのか)を出した方が個人的に良いと思ってます。(空白で出されてもなって感じ)
藤下さんに確認した方が良いかなと思います。

2023-07-15 07:25 UTC, HiroakiKonnno commented on app/helpers/documents_helper.rb
> +
request_order_uuidがnilなことは起こり得ないと思ってます。
request_order.parent_idがnilの時(閲覧が元請の時)に@parent_request_orberと@parent_request_orber.businessがnilで返ればいいと思います。

具体的に言えば既存のコードの
``````
@parent_request_orber = RequestOrder.find(request_order.parent_id)
 @parent_business = @parent_request_orber.business
``````
を
``````
@parent_request_orber = RequestOrder.find_by(id: request_order.parent_id)
@parent_business = @parent_request_orber&.business
``````
にすれば元請閲覧の時は両方nilで返ると思います。

可読性を上げるのであれば
``````
if request_order.parent_id.ni?
``````
とかで処置してあげるといいかと思います。
(もっというとmodelにparent_idがnilの時を元請で定義したいなーと)

2023-07-15 07:25 UTC, HiroakiKonnno commented on app/helpers/documents_helper.rb
> +
@parent_request_orberがorberではなくorderと思うので修正した方が良いと思います。
(既存コードが間違っていますが)

2023-07-17 07:28 UTC, badminto commented on app/helpers/documents_helper.rb
> +
@HiroakiKonnno 
レビューありがとうございます！
ご指摘頂いた箇所の修正を行いました。金野さんがしてほしいことと違うことをしているかもしれません😖
ご確認お願いいたします🙇

2023-07-17 08:45 UTC, HiroakiKonnno requested changes
修正ありがとうございます！
意図は伝わっていそうですが、修正不足箇所にコメントしました！
確認をお願いいたします！

2023-07-17 08:45 UTC, HiroakiKonnno commented on app/helpers/documents_helper.rb
> +    if @parent_request_order&.parent?
メソッド化してるのはgoodです！
ただ@parent_request_order&.parent?では全ての結果がnilにはならないでしょうか？？
確認をお願いいたします！(30分考えて理由わからなければ連絡願います。)
⇨ テストコードを書かないのであれば、せめて意図通りの動きになるかを確認した方が良いかと思いました！
(意図通りの動きをしていて、僕の勘違いであればすみません)

あとelse節で
@parent_request_order  = nil
@parent_business  = nilの方が分かりやすい気がしました。

2023-07-17 08:45 UTC, HiroakiKonnno commented on app/models/request_order.rb
> +  def parent?
メソッド化の意図はあってます！いいですねー！！
もう少し厳密にいくと、parent?(親ですか？)って聞きたいんではなくて、
prime_contractor?(元請ですか？)って聞きたいんじゃないでしょうか？

2023-07-17 08:55 UTC, badminto commented on app/models/request_order.rb
> +  def parent?
@HiroakiKonnno 
そうですね😅修正いたします！🫡

2023-07-17 09:18 UTC, badminto commented on app/helpers/documents_helper.rb
> +    if @parent_request_order&.parent?
@HiroakiKonnno 
「下請けは親ですか？」 → 違います → nil　なので全てnilになると思いました！
もう一度動きを確認します🙇

2023-07-17 09:21 UTC, HiroakiKonnno commented on app/helpers/documents_helper.rb
> +    if @parent_request_order&.parent?
@badminto 
違います！
@parent_request_orderはどこに定義されているのですか？がヒントです。

2023-07-17 09:37 UTC, badminto commented on app/helpers/documents_helper.rb
> +    if @parent_request_order&.parent?
1609行目のメソッド内に定義されているため、「@parent_request_order」は全てnilになってしまう。
ということでしょうか...??😓

2023-07-17 09:49 UTC, HiroakiKonnno commented on app/helpers/documents_helper.rb
> +    if @parent_request_order&.parent?
@badminto 
ですね！
あくまで推測ですが気づくタイミングはあったかと思います！
``````
@parent_request_order.parent?
``````
でno method error for nil classが出たので

``````
@parent_request_order&.parent?
``````
としたのでは？と思っています！

もし上記推測が当たっているなら
とりあえずボッチ関数使ってエラー解決したからいいやーに留めないほうが今後のために良いと思います！

2023-07-17 10:08 UTC, badminto commented on app/helpers/documents_helper.rb
> +    if @parent_request_order&.parent?
@HiroakiKonnno 
上記の流れの通りです！
ありがとうございます！承知致しました！修正致します🙇

2023-07-21 23:10 UTC, badminto commented on app/helpers/documents_helper.rb
> +    if @parent_request_order&.parent?
@HiroakiKonnno 
お疲れ様です！
修正いたしました！ご確認お願い致します🙇

2023-07-21 23:10 UTC, badminto commented on app/models/request_order.rb
> +  def parent?
@HiroakiKonnno 
お疲れ様です！
修正いたしました！ご確認お願い致します🙇

2023-07-21 23:18 UTC, HiroakiKonnno approved these changes
動きはするのでLGTMです！

2023-07-21 23:18 UTC, HiroakiKonnno commented on app/helpers/documents_helper.rb
> +      @parent_request_order = RequestOrder.find(request_order.parent_id)
request_order.parentで取得できると思います。

2023-07-21 23:18 UTC, HiroakiKonnno commented on app/helpers/documents_helper.rb
> +    if request_order&.prime_contractor?
ボッチ関数にする意味はないと思います。

2023-07-22 09:02 UTC, badminto commented on app/helpers/documents_helper.rb
> +    if request_order&.prime_contractor?
@HiroakiKonnno 
ボッチ関数を削除しました。ご確認お願い致します🙇

2023-07-22 09:03 UTC, badminto commented on app/helpers/documents_helper.rb
> +      @parent_request_order = RequestOrder.find(request_order.parent_id)
@HiroakiKonnno 
request_order.parentで取得するように修正を行いました。ご確認お願い致します🙇

2023-07-23 12:28 UTC, toshihiro-mabuchi approved these changes

2023-07-23 12:28 UTC, merged